version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  apt_packages:
    - libgl1-mesa-glx 
    - xvfb

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/source/conf.py